=begin
#Klaviyo API

#The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

Contact: developers@klaviyo.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module KlaviyoAPI
  class TriggerBranchActionData
    attr_accessor :trigger_filter

    attr_accessor :trigger_id

    # Trigger type.
    attr_accessor :trigger_type

    # Date trigger type.
    attr_accessor :trigger_subtype

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'trigger_filter' => :'trigger_filter',
        :'trigger_id' => :'trigger_id',
        :'trigger_type' => :'trigger_type',
        :'trigger_subtype' => :'trigger_subtype'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'trigger_filter' => :'TriggerBranchActionDataTriggerFilter',
        :'trigger_id' => :'String',
        :'trigger_type' => :'String',
        :'trigger_subtype' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'trigger_filter',
        :'trigger_subtype'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KlaviyoAPI::TriggerBranchActionData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KlaviyoAPI::TriggerBranchActionData`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'trigger_filter')
        self.trigger_filter = attributes[:'trigger_filter']
      end

      if attributes.key?(:'trigger_id')
        self.trigger_id = attributes[:'trigger_id']
      end

      if attributes.key?(:'trigger_type')
        self.trigger_type = attributes[:'trigger_type']
      end

      if attributes.key?(:'trigger_subtype')
        self.trigger_subtype = attributes[:'trigger_subtype']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @trigger_id.nil?
        invalid_properties.push('invalid value for "trigger_id", trigger_id cannot be nil.')
      end

      if @trigger_type.nil?
        invalid_properties.push('invalid value for "trigger_type", trigger_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @trigger_id.nil?
      return false if @trigger_type.nil?
      trigger_type_validator = EnumAttributeValidator.new('String', ["date", "list", "low-inventory", "metric", "price-drop", "scheduled", "segment"])
      return false unless trigger_type_validator.valid?(@trigger_type)
      trigger_subtype_validator = EnumAttributeValidator.new('String', ["custom-object", "legacy-custom-object", "profile-property", "profile-trait"])
      return false unless trigger_subtype_validator.valid?(@trigger_subtype)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] trigger_type Object to be assigned
    def trigger_type=(trigger_type)
      validator = EnumAttributeValidator.new('String', ["date", "list", "low-inventory", "metric", "price-drop", "scheduled", "segment"])
      unless validator.valid?(trigger_type)
        fail ArgumentError, "invalid value for \"trigger_type\", must be one of #{validator.allowable_values}."
      end
      @trigger_type = trigger_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] trigger_subtype Object to be assigned
    def trigger_subtype=(trigger_subtype)
      validator = EnumAttributeValidator.new('String', ["custom-object", "legacy-custom-object", "profile-property", "profile-trait"])
      unless validator.valid?(trigger_subtype)
        fail ArgumentError, "invalid value for \"trigger_subtype\", must be one of #{validator.allowable_values}."
      end
      @trigger_subtype = trigger_subtype
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          trigger_filter == o.trigger_filter &&
          trigger_id == o.trigger_id &&
          trigger_type == o.trigger_type &&
          trigger_subtype == o.trigger_subtype
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [trigger_filter, trigger_id, trigger_type, trigger_subtype].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = KlaviyoAPI.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
